# Generated by Django 4.1.6 on 2023-02-02 14:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "inscricao"},
        ),
    ]
