# Generated by Django 4.1.6 on 2023-02-02 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_options_alter_user_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="data_inscricao",
        ),
    ]
